name: Deployment Pipeline

on: 
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16    
      - name: Install dependencies
        run: npm ci
      - name:  Lint
        run: npm run eslint --no-audit --no-fund --no-optional
      - name: Build
        run: npm run build --no-audit --no-fund --no-optional
      - name: Test
        run: npm test
      - name: E2E Test 
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          command: npm run test:e2e
          wait-on: http://localhost:5000
      - name: Deployment
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.VERCEL_ID}}  
          vercel-project-id: ${{ secrets.PROJECT_ID}}